spring:
  application:
    name: his-backend
  
  datasource:
    url: jdbc:postgresql://db.xsozisuoykdqtshyhrkd.supabase.co:5432/postgres
    username: postgres
    password: fzk#k92a/GsENV7
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
