ALTER TABLE drugs ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE drugs ADD COLUMN is_narcotic BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE drugs ADD COLUMN reorder_level INTEGER NOT NULL DEFAULT 100;
